<?php
namespace pcd\search;

use Carbon\Carbon;
use Illuminate\Support\Arr;
use pcd\models\CabenhSxh;
use pcd\models\Chuyenca;
use pcd\models\HcPhuong;
use pcd\models\HcQuan;
use pcd\supports\RoleHc;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\db\Expression;

class CabenhSxhSearch extends CabenhSxh
{
    public $date_from;
    public $date_to;
    public $loaica;
    public $group_xm;
    public $excepted_tv;
    public $field_date;
    public $cabenh_ids;
    public $tiendo_lv;

    public function init()
    {
        parent::init();
        $this->field_date = 'ngaybaocao';
        $this->date_from = '01/01/2019';
    }


    public static function tableName()
    {
        return 'v_phieu_dt';
    }

    public function rules()
    {
        return [
            [['loaidieutra', 'loaicabenh', 'loaibaocao', 'chuandoan', 'loaixacminh_cb', 'ht_dieutri', 'is_nghingo', 'loai_xm_cb', 'group_xm', 'excepted_tv'], 'integer'],
            [['chuandoan_bd', 'hoten', 'phai', 'tuoi', 'dienthoai', 'sonha', 'duong', 'to_dp', 'khupho', 'maquan', 'maphuong', 'nghenghiep'], 'string'],
            [['ngaybaocao', 'ngaynhapvien', 'ngayxuatvien', 'date_from', 'date_to'], 'date', 'format' => 'php:d/m/Y'],
            [['tiendo_lv', 'loaica'], 'integer'],
            [['cabenh_ids'], 'string']
        ];
    }

    public static function primaryKey()
    {
        return parent::primaryKey(); // TODO: Change the autogenerated stub
    }


    public function scenarios()
    {
        return Model::scenarios();
    }

    public function search($params)
    {
        $roles = RoleHc::init();
        $query = $this->find()->with([
            'hcPhuong'
        ]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => ['defaultOrder' => ['gid' => SORT_DESC]],
            'pagination' => [
                'defaultPageSize' => 10,
            ],
        ]);

        $this->load($params);
        $this->setAttributes(Arr::only($params, ['cabenh_ids']));

        if (!$this->validate()) {
            $query->where('0=1');
            return $dataProvider;
        }

        $query->andFilterWhere([
            'loaidieutra' => $this->loaidieutra,
            'loaicabenh' => $this->loaicabenh,
            'chuandoan_bd' => $this->chuandoan_bd,
            'phai' => $this->phai,
            'chuandoan' => $this->chuandoan,
            'loaixacminh_cb' => $this->loaixacminh_cb,
            'ht_dieutri' => $this->ht_dieutri,
            'loai_xm_cb' => $this->loai_xm_cb,
        ]);

        if(!in_array($this->loaica, [2,3,4])){
            $query->andFilterWhere([
                'maphuong' => $this->maphuong,
                'maquan' => $this->maquan,
            ]);
        }

        if($this->date_from){
            $query->andFilterWhere(['>=', $this->field_date, dateToDb($this->date_from)]);
        }

        if($this->date_to){
            $query->andFilterWhere(['<=', $this->field_date, dateToDb($this->date_to)]);
        }

        if($this->khupho == 'KHONG RO'){
            $this->khupho = null;
            $query->andWhere('khupho IS NULL');
        }


        $query
            ->andFilterSearch(['ilike', 'hoten', $this->hoten])
            ->andFilterSearch(['ilike', 'tuoi', $this->tuoi])
            ->andFilterSearch(['ilike', 'dienthoai', $this->dienthoai])
            ->andFilterSearch(['ilike', 'sonha', $this->sonha])
            ->andFilterSearch(['ilike', 'to_dp', $this->to_dp])
            ->andFilterSearch(['ilike', 'khupho', $this->khupho])
            ->andFilterSearch(['ilike', 'duong', $this->duong])
            ->andFilterSearch(['ilike', 'nghenghiep', $this->nghenghiep])
            ->andFilterWhere(['=', 'ngaynhapvien', $this->ngaynhapvien])
            ->andFilterWhere(['=', 'ngayxuatvien', $this->ngayxuatvien]);

        if($group_xm = $this->group_xm){
            if($group_xm == 1){
                $query->andWhere(['in', 'loai_xm_cb', [7, 8]]);
            } else if($group_xm == 2) {
                $query->andWhere(['in', 'loai_xm_cb', [4, 5, 6]]);
            } else{
                $query->andWhere(['in', 'loai_xm_cb', [1, 2, 3]]);
            }
        }


        $roles->filterChuyenCa($this->loaica, $query);

        if($this->cabenh_ids) {
            if(role('phuong')){
                $giapranh = data_get(HcPhuong::find()->andFilterWhere(['maphuong' => userInfo()->maphuong])->one(), 'giapranh.items');
                $query->orFilterWhere(['in', 'maphuong', $giapranh]);
            } elseif (role('quan')){
                $giapranh = data_get(HcQuan::find()->andFilterWhere(['maquan' => userInfo()->maquan])->one(), 'giapranh.items');
                $query->orFilterWhere(['in', 'maquan', $giapranh]);
            }

            $query->andFilterWhere(['in', 'gid', explode(',', $this->cabenh_ids)]);
        };

        if($this->tiendo_lv == '1'){
            $query->andWhere("deadline_at IS NULL OR timezone('Asia/Ho_Chi_Minh', now()) <= deadline_at");
        }

        if($this->tiendo_lv == '2'){
            $query->andWhere("timezone('Asia/Ho_Chi_Minh', now()) > deadline_at");
        }

        return $dataProvider;
    }

    public function fields()
    {
        return [
            'gid',
            'hoten',
            'diachi' => function ($model) {
                $tenphuong = data_get($model, 'hcPhuong.tenphuong');
                $tenquan = data_get($model, 'hcPhuong.tenquan');
                return $this->toAddress($model->sonha, $model->duong, $model->to_dp, $model->khupho, $tenphuong, $tenquan);
            },
            'ngaybaocao',
            'ngaymacbenh',
            'ngaynhapvien',
            'ngaymacbenh_nv',
            'loaidieutra',
            'loaixacminh_cb',
            'chuandoan_bd',
            'chuandoan_khac',
            'chuandoan',
            'chuandoan_khac',
            'loai_xm_cb',
            'geometry' => function ($model) {
                return $model->toGeometry();
            },
        ];
    }
}