<?php
namespace pcd\search;

use Carbon\Carbon;
use pcd\models\CabenhSxh;
use pcd\models\Chuyenca;
use pcd\supports\RoleHc;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\db\Expression;

class CabenhSxhSearch extends CabenhSxh
{
    public $date_from;
    public $date_to;
    public $loaica;
    public $group_xm;
    public $excepted_tv;
    public $field_date;

    public function init()
    {
        parent::init();
        $this->field_date = 'ngaybaocao';
        $this->date_from = '01/01/2019';
    }


    public static function tableName()
    {
        return 'v_phieu_dt';
    }

    public function rules()
    {
        return [
            [['loaidieutra', 'loaicabenh', 'loaibaocao', 'chuandoan', 'loaixacminh_cb', 'ht_dieutri', 'is_nghingo', 'loai_xm_cb', 'group_xm', 'excepted_tv'], 'integer'],
            [['chuandoan_bd', 'hoten', 'phai', 'tuoi', 'dienthoai', 'sonha', 'duong', 'to_dp', 'khupho', 'maquan', 'maphuong', 'nghenghiep'], 'string'],
            [['ngaybaocao', 'ngaynhapvien', 'ngayxuatvien', 'date_from', 'date_to'], 'date', 'format' => 'php:d/m/Y'],
            [['loaica'], 'integer']
        ];
    }

    public static function primaryKey()
    {
        return parent::primaryKey(); // TODO: Change the autogenerated stub
    }


    public function scenarios()
    {
        return Model::scenarios();
    }

    public function search($params)
    {
        $roles = RoleHc::init();
        $query = $this->find()->where(['is_nghingo' => null])->with([
            'hcPhuong'
        ]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => ['defaultOrder' => ['gid' => SORT_DESC]],
            'pagination' => [
                'defaultPageSize' => 10,
            ],
        ]);

        $this->load($params);

        if (!$this->validate()) {
            $query->where('0=1');
            return $dataProvider;
        }

        $query->andFilterWhere([
            'maphuong' => $this->maphuong,
            'maquan' => $this->maquan,
            'loaidieutra' => $this->loaidieutra,
            'loaicabenh' => $this->loaicabenh,
            'chuandoan_bd' => $this->chuandoan_bd,
            'phai' => $this->phai,
            'chuandoan' => $this->chuandoan,
            'loaixacminh_cb' => $this->loaixacminh_cb,
            'ht_dieutri' => $this->ht_dieutri,
            'loai_xm_cb' => $this->loai_xm_cb,
        ]);



        if($this->date_from){
            $query->andFilterWhere(['>=', $this->field_date, dateToDb($this->date_from)]);
        }

        if($this->date_to){
            $query->andFilterWhere(['<=', $this->field_date, dateToDb($this->date_to)]);
        }

        $query
            ->andFilterSearch(['ilike', 'hoten', $this->hoten])
            ->andFilterSearch(['ilike', 'tuoi', $this->tuoi])
            ->andFilterSearch(['ilike', 'dienthoai', $this->dienthoai])
            ->andFilterSearch(['ilike', 'sonha', $this->sonha])
            ->andFilterSearch(['ilike', 'to_dp', $this->to_dp])
            ->andFilterSearch(['ilike', 'khupho', $this->khupho])
            ->andFilterSearch(['ilike', 'duong', $this->duong])
            ->andFilterSearch(['ilike', 'nghenghiep', $this->nghenghiep])
            ->andFilterWhere(['=', 'ngaybaocao', $this->ngaybaocao])
            ->andFilterWhere(['=', 'ngaynhapvien', $this->ngaynhapvien])
            ->andFilterWhere(['=', 'ngayxuatvien', $this->ngayxuatvien]);

        if($group_xm = $this->group_xm){
            if($group_xm == 1){
                $query->andWhere(['in', 'loai_xm_cb', [7, 8]]);
            } else if($group_xm == 2) {
                $query->andWhere(['in', 'loai_xm_cb', [4, 5, 6]]);
            } else{
                $query->andWhere(['in', 'loai_xm_cb', [1, 2, 3]]);
            }
        }



        if($et = $this->excepted_tv){
            if($et == 1){
                $query->andWhere(['not', ['is_trave' => 1]]);
            }
        }


        $roles->filterChuyenCa($this->loaica, $query);


//        dd($params);
//        dd($query->createCommand()->getRawSql());

        return $dataProvider;
    }

    public function fields()
    {
        return [
            'gid',
            'hoten',
            'diachi' => function ($model) {
                $tenphuong = data_get($model, 'hcPhuong.tenphuong');
                $tenquan = data_get($model, 'hcPhuong.tenquan');
                return $this->toAddress($model->sonha, $model->duong, $model->to_dp, $model->khupho, $tenphuong, $tenquan);
            },
            'ngaybaocao',
            'ngaymacbenh',
            'ngaynhapvien',
            'ngaymacbenh_nv',
            'loaidieutra',
            'loaixacminh_cb',
            'chuandoan_bd',
            'chuandoan_khac',
            'chuandoan',
            'chuandoan_khac',
            'loai_xm_cb',
            'geometry' => function ($model) {
                return $model->toGeometry();
            },
        ];
    }
}